[project]
name = "dumps-or-fire"
version = "1.1.0"
description = "Music Popularity Getter Website"
authors = [
    { name = "Joshua Holman", email = "jolman@duck.com" },
    { name = "Brandon Cobb" },
    { name = "Jarred Siriban" }
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "Django>=5.1.0",
    "logger>=1.4",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
    "social-auth-app-django>=5.4.0",
]

[project.urls]
Homepage = "https://github.com/thejolman/dumps-or-fire"

[project.optional-dependencies]
dev = [
    "black",
    "pytest",
    "mypy",
]
